services:
  devcontainer:
    container_name: development-service
    build: 
      context: .devcontainer
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached      
    command: sleep infinity
    ports:
      - "8000:8000"

  api-service:
    container_name: api-service
    build:
      context: api_service
      dockerfile: Dockerfile
    network_mode: service:devcontainer   # Puts app and devcontainer in the same network so browsing http://127.0.0.1:8080 works
    environment:
      - PORT=8000