name: CI/CD Workflows Orchestrator
run-name: CI/CD Workflows Orchestrator for ${{ github.event.repository.name }}
on:
    push:
        branches:
            - '**'

env:
    SERVICE_NAME_PREFIX: rmr-projection-

jobs:
    extract-service-name:
        name: Extract Service Name
        runs-on: ubuntu-latest
        outputs:
            SERVICE_NAME: ${{ steps.extract.outputs.SERVICE_NAME }}
        steps:
            - name: Extract Service Name
              id: extract
              run: |
                  repository_name=${{ github.event.repository.name }}
                  SERVICE_NAME=${repository_name#*${{ env.SERVICE_NAME_PREFIX }}}
                  echo "SERVICE_NAME=${SERVICE_NAME}" >> ${GITHUB_OUTPUT}
                  echo "Service name extracted '${SERVICE_NAME}' from repository name '${repository_name}'"

    extract-environment-name:
        name: Extract Environment Name
        runs-on: ubuntu-latest
        outputs:
            ENVIRONMENT: ${{ steps.extract.outputs.ENVIRONEMNT }}
        steps:
            - name: Extract Environment Name
              id: extract
              run: |
                  branch=${{ github.ref_name }}
                  case "${branch}" in
                      main)
                          ENVIRONMENT='production'
                          echo "ENVIRONMENT=${ENVIRONMENT}"
                          echo "Environment set to '${ENVIRONMENT}' for branch '${branch}'"
                          ;;
                      alpha)
                          ENVIRONMENT='alpha'
                          echo "ENVIRONMENT=${ENVIRONMENT}"
                          echo "Environment set to '${ENVIRONMENT}' for branch '${branch}'"
                          ;;
                      dev)
                          ENVIRONMENT='development'
                          echo "ENVIRONMENT=${ENVIRONMENT}"
                          echo "Environment set to '${ENVIRONMENT}' for branch '${branch}'"
                          ;;
                      *)
                          echo "No specific environment set for branch '${branch}'"
                          ;;
                      esac

    quality-security:
        name: Code Quality, Unit Tests, Security Checks, and Reports
        uses: ./.github/workflows/quality-security.yaml
        secrets: inherit

    push-docker-hub:
        name: Build Docker Image and Push to Docker Hub
        if: github.ref == 'refs/heads/dev'
        needs:
            - extract-service-name
            - extract-environment-name
            - quality-security
        uses: ./.github/workflows/push-docker-hub.yaml
        with:
            SERVICE_NAME: ${{ needs.extract-service-name.outputs.SERVICE_NAME }}
        secrets: inherit

    release:
        name: Make Release
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/alpha'
        needs:
            - extract-service-name
            - extract-environment-name
            - quality-security
        uses: ./.github/workflows/release.yaml

    push-gar:
        name: Build Docker Image and Push to Google Artifact Registry
        needs:
            - extract-service-name
            - extract-environment-name
            - release
        uses: ./.github/workflows/push-gar.yaml
        with:
            SERVICE_NAME: ${{ needs.extract-service-name.outputs.SERVICE_NAME }}
            ENVIRONMENT: ${{ needs.extract-environment-name.outputs.ENVIRONMENT}}
            RELEASE_TAG: ${{ needs.release.outputs.RELEASE_TAG }}
        secrets: inherit

    dispatch:
        name: Dispatch Data to IaC Repository
        needs:
            - extract-service-name
            - extract-environment-name
            - release
            - push-gar
        uses: ./.github/workflows/dispatch.yaml
        with:
            SERVICE_NAME: ${{ needs.extract-service-name.outputs.SERVICE_NAME }}
            INGRESS_PORT: '8000'
            INGRESS_ENV_VARS: '[{"name":"OTEL_SERVICE_NAME","value":"${{ needs.extract-service-name.outputs.SERVICE_NAME }}"},{"name":"OTLP_ENDPOINT","value":"http://localhost:4317"}]'
            ENVIRONMENT: ${{ needs.extract-environment-name.outputs.ENVIRONMENT }}
            RELEASE_TAG: ${{ needs.release.outputs.RELEASE_TAG }}
            SIDECAR_NAME: 'alloy'
            SIDECAR_RELEASE_TAG: 'v1.0.0'
        secrets: inherit
